import streamlit as st
st.title("streamlit Demo")
st.header("This is Header")
st.subheader("This is Subheader")
st.markdown("--------")
st.success("this is green")
st.error("this is red")
st.info("this is yellow")
st.warning("this is blue")
st.markdown("---")